# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ACCI_Cricket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ReachabilitySwift'
  pod 'SVProgressHUD'
  pod 'JVFloatLabeledTextField'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'


  # Pods for ACCI_Cricket

  target 'ACCI_CricketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ACCI_CricketUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
